### ISSUE TITLE
 [ERROR]Couldn't place player in world

### ISSUE THREAD

**Issue by lamya3** [akshualy/AntiSeedCracker#6]
```
[22:34:29 ERROR]: Couldn't place player in world
net.minecraft.ReportedException: Sending packet
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2257) ~[?:?]        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2227) ~[?:?]        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:397) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:203) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:184) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:86) ~[?:?]        at net.minecraft.network.Connection.tick(Connection.java:603) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1600) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:456) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:309) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.NullPointerException: type cannot be null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.1-jre.jar:?]
        at com.comphenix.protocol.injector.StructureCache.getStructure(StructureCache.java:138) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:126) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:96) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:450) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:393) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2249) ~[?:?]        ... 13 more
```
And client will be issued `invalid player data`

**Comment by akshualy** [comment]
Which server and Minecraft version are you running?

**Comment by Ingrim4** [comment]
Should be fixed in the latest dev build of ProtocolLib so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by lamya3** [comment]
> Which server and Minecraft version are you running?

LeavesMC 1.20.1

**Comment by lamya3** [comment]
> Should be fixed in the latest dev build of ProtocolLib so please use the latest dev build and try again: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

yep it fixed my problem too
